#!/usr/bin/bash 
echo 1 | echo 2 | echo 3 | echo 4

(echo 1 | echo 2 || echo 3) && (echo 4 || echo 5 | echo 6)

(/bin/echo 1 | /bin/echo 2) && (/bin/echo 3 | /bin/echo 3 | /bin/echo 4 | /bin/echo 4)

(sleep 0 && (exit 4))

exit 2
